# Default values for helm-guestbook.
# This is a YAML-formatted file.

replicaCount: 2

image:
  repository: marioscloud/my-python-app
  tag: "013b01c81b3165f6e785ea3a340877f41c87ab33"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}

# Custom variable used in rollout.yaml
containerPort: 5000
